version: '3'

services:
  postgres:
      image: postgres:14-alpine
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=db_tasks

  service:
    build:
      context: .
      dockerfile: ./server.dockerfile
    restart: always
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/db_tasks?sslmode=disable
    ports:
      - "8080:8080"